name: Draft

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  id-token: write
  pull-requests: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
        
        - name: macOS
          os: macos-latest
        
        - name: Linux
          os: ubuntu-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Cargo Registry and Builds
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
    - name: Add x64 for macOS
      if: contains(matrix.config.os, 'macos')
      run: rustup target add x86_64-apple-darwin

    - name: Build
      run: |
        cargo build --release --verbose

    - name: Build for Intel Macs
      if: contains(matrix.config.os, 'macos')
      run: |
        cargo build --release --verbose --target x86_64-apple-darwin

    - name: Combine macOS Builds
      if: contains(matrix.config.os, 'macos')
      run: |
        lipo -create \
           target/release/cargofetch \
           target/x86_64-apple-darwin/release/cargofetch \
           -output target/release/cargofetch

    - name: Change File Names
      shell: bash
      id: rename
      run: |
        version=$(grep '^version\s*=' Cargo.toml | head -n 1 | cut -d '"' -f 2)
        if [[ ${{ matrix.config.os }} == 'windows-latest' ]]; then
          echo "releasefilename=cargofetch-release-${version}.exe" >> $GITHUB_OUTPUT
          mv target/release/cargofetch.exe target/release/cargofetch-release-${version}.exe
        elif [[ ${{ matrix.config.os }} == 'macos-latest' ]]; then
          echo "releasefilename=cargofetch-release-${version}-macos" >> $GITHUB_OUTPUT
          mv target/release/cargofetch-universal target/release/cargofetch-release-${version}-macos
        else
          echo "releasefilename=cargofetch-release-${version}-linux" >> $GITHUB_OUTPUT
          mv target/release/cargofetch target/release/cargofetch-release-${version}-linux
        fi

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.rename.outputs.releasefilename }}
        path: target/release/${{ steps.rename.outputs.releasefilename }}

  package:
    name: Package Builds
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: cargofetch
    - name: Get Version
      id: get_version
      run: |
        version=$(grep '^version\s*=' ./cargofetch/Cargo.toml | head -n 1 | cut -d '"' -f 2)
        echo "version=${version}" >> $GITHUB_ENV
    - uses: actions/download-artifact@v4
      with:
        path: "artifacts2"

    - name: move artifacts
      run: |
        mkdir artifacts
        mv artifacts2/*/* artifacts
    

    - name: Make Draft Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.version }}
        name: 'Cargofetch v${{ env.version }}'
        draft: true
        body: ${{ steps.changelog.outputs.changelog }}
        files: |
          artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
